obj-$(CONFIG_ARCH_SDP83)	+= sdp83.o sdp83_clock.o
obj-$(CONFIG_MACH_LEONID)	+= mach-leonid.o

obj-$(CONFIG_ARCH_SDP92)	+= sdp92.o sdp92_clock.o
obj-$(CONFIG_MACH_AQUILA)	+= mach-aquila.o

obj-$(CONFIG_ARCH_SDP93)	+= sdp93.o sdp93_clock.o
obj-$(CONFIG_MACH_CORONA)	+= mach-corona.o

obj-$(CONFIG_SDP83_GPIO)	+= sdp83_gpio.o
obj-$(CONFIG_SDP92_GPIO)	+= sdp92_gpio.o

