obj-y				:= sdp_irq.o
obj-$(CONFIG_SDP_TIMER)		+= sdp_timer.o
obj-$(CONFIG_HIGH_RES_TIMERS)	+= sdp_hrtimer.o
obj-$(CONFIG_SDP_GPIO)		+= sdp_gpio.o
#obj-$(CONFIG_SDP_I2C)		+= sdp_i2c.o
obj-$(CONFIG_SDP_I2C)		+= sdp_i2c_edid.o

#UART
#obj-$(CONFIG_SERIAL_SDP) 	+= s5h2x_uart.o 

#Ethernet
obj-$(CONFIG_SDP_GMAC)		+= sdpGmac/

#PCI
obj-$(CONFIG_SDP_PCI)		+= pci.o sdp_pci.o 
obj-$(CONFIG_SDP_PCIE)		+= pcie.o sdp_pcie.o 
#obj-$(CONFIG_SDP_PCIE)		+= sdpPcie/

#SATA
#obj-$(CONFIG_SDP_SATA)		+= sdpSata/

