
###################################################
# Makefile for the Synopsys GMAC driver
###################################################

sdpGMAC-objs :=	sdpGmacInit.o sdpGmacBase.o

obj-$(CONFIG_SDP_GMAC) += sdpGMAC.o


