#Add for Advanced OProfile

obj-$(CONFIG_ADVANCE_OPROFILE) += aop_oprofile.o
obj-$(CONFIG_ADVANCE_OPROFILE) += aop_report.o
obj-$(CONFIG_ADVANCE_OPROFILE) += aop_kernel.o
obj-$(CONFIG_ADVANCE_OPROFILE) += aop_report_symbol.o
obj-$(CONFIG_ADVANCE_OPROFILE) += aop_elf_parser.o
obj-$(CONFIG_ADVANCE_OPROFILE) += aop_read_dir.o
obj-$(CONFIG_ADVANCE_OPROFILE) += aop_demangle.o
