@ifndef CROSS_ENDIAN_H
@define CROSS_ENDIAN_H 1

#include <endian.h>

@define CROSS_BIG_ENDIAN 1
@define CROSS_LITTLE_ENDIAN 2
#if __BYTE_ORDER == __LITTLE_ENDIAN
@define CROSS_BYTE_ORDER CROSS_LITTLE_ENDIAN
#else
@define CROSS_BYTE_ORDER CROSS_BIG_ENDIAN
#endif

@endif
