@ifndef LD_CONFIG_H
@define LD_CONFIG_H

@include_leaf ldconfig.h

@copy FLAG_ANY
@copy FLAG_TYPE_MASK
@copy FLAG_LIBC4
@copy FLAG_ELF
@copy FLAG_ELF_LIBC5
@copy FLAG_ELF_LIBC6
@copy FLAG_REQUIRED_MASK
@copy FLAG_SPARC_LIB64
@copy FLAG_IA64_LIB64
@copy FLAG_X8664_LIB64
@copy FLAG_S390_LIB64
@copy FLAG_POWERPC_LIB64
@copy FLAG_MIPS64_LIBN32
@copy FLAG_MIPS64_LIBN64

@copy SYSDEP_KNOWN_INTERPRETER_NAMES
@copy SYSDEP_KNOWN_LIBRARY_NAMES

@endif
